export LIBCONFIG=n
export CMCONF=y
export BASE64=y
export LIBJSON=n
export KFCRYPTO=y
export CMNET=y
export CMFLASH=y
export CMUART=y
export NGXMD5=y
export KFOPENSSL_AES=y
export LLHTTP=y
export CMEX=y
export CMEXJSON=n
export JANSSON=y
export PROGDEBUG=y

export USE_LIBCURL=n
#export CFLAGS += -Ixxxlibcurl include path
#export LINKPATH += -Lxxx libcurl lib path

export DISK=n
export CODEC=n
export VDEV=n
export BVSTREAM=n
export DEMO=n
export RECORDSERVER=n
export OPENAV=y
export OPENGL=y
export QRCODE=n
