###
## Change it only when you add new file to compile
## other config please see config/...
## config.mk is generated by Makefile, so don't change it.

SHELL=/bin/bash

BASEDIR=$(shell pwd)

sinclude config/config_all.mk


## this is defined in config/config_all.mk
#filedirs-y=common disk stream
.PHONY: $(filedirs-y)

all: createdir $(filedirs-y) dep-before static dyn

common:
	@$(ECHO) "\n\t GOTO BUILD $@ \n"
	@cd $@; make; \
	cd ..

disk:
	@$(ECHO) "\n\t GOTO BUILD $@ \n"
	@cd $@; make; cd ..

## add jk_stream_ex.o to OBJS_MAIN for recompile if change the content.
stream:
	@$(ECHO) "\n\t GOTO BUILD $@ \n"
	@cd $@; make; cd ..

vdev:
	@$(ECHO) "\n\t GOTO BUILD $@ \n"
	@cd $@; make; cd ..

codec:
	@$(ECHO) "\n\t GOTO BUILD $@ \n"
	@cd $@; make; cd ..

## check build-in files before make static and dyn
dep-before:
	@for i in $(buildin-files); do   \
		if [ ! -f $$i ] ; then   \
			$(ECHO) "\n\t[ $$i ] not exist, so exit!\n";   \
			exit 1;    \
		fi;    \
	done


static:
	@$(ECHO) " \t Generate \t $(STATIC_JKLIB)"
	$(Q) $(AR) -r -o $(LIBDIR_PATH)/$(STATIC_JKLIB) $(buildin-files)
	$(Q) ln -sf $(LIBDIR_PATH)/$(STATIC_JKLIB) $(LIBDIR_PATH)/$(LINKSTATICJK)

dyn:
	@$(ECHO) " \t Generate \t $(DYNJKLIB)"
	$(Q) $(CC) -fPIC -shared -o $(LIBDIR_PATH)/$(DYNJKLIB) $(buildin-files)
	$(Q) ln -sf $(LIBDIR_PATH)/$(DYNJKLIB) $(LIBDIR_PATH)/$(LINKJK)

dep:
	@if [ ! -d $(HOME)/libs ]; then   \
	 $(ECHO) "No $(HOME)/libs directory, please svn co http://192.168.6.16/svn/application/binary/libs ${HOME}/libs";   \
	 exit 1;   \
	 fi


createdir:
	@if [ ! -f config.mk ]; then   \
		$(ECHO) "    No platform, please exec: "; \
		$(ECHO) "    make x86/hi3515/dm365/hi3535";  \
		exit 1; \
	fi	
	@mkdir -p $(OBJDIR)  
	@mkdir -p $(INSTALL_DIRS)/lib

install:
	@$(ECHO) "\t cp $(INSTALL_HEADERS) $(INSTALL_DIRS)/include/"
	$(Q) cp $(INSTALL_HEADERS) $(INSTALL_DIRS)/include/
	$(Q) cp $(INSTALL_LIBS) $(INSTALL_DIRS)/lib/

clean:
	@for i in $(filedirs-y); do   \
		echo ""; \
		cd $$i; make clean; cd ..;   \
		echo ""; \
	done
	rm outlib/$(OS)/lib/* -rf

distclean: clean
	$(Q)rm -rf .obj*

help:
	@$(ECHO) "\t make x86/dm6446/dm365/hi3515/hi3518/hi3535"
	@$(ECHO) "\t make DEBUG [optional]"

x86:
	@$(ECHO) "OS=x86" > config.mk

dm6446:
	@$(ECHO) "OS=dm6446" > config.mk

dm365:
	@$(ECHO) "OS=dm365" > config.mk

rasp3:
	@$(ECHO) "OS=rasp3" > config.mk

hi3515:
	@$(ECHO) "OS=hi3515" > config.mk

hi3518:
	@$(ECHO) "OS=hi3518" > config.mk

hi3535:
	@$(ECHO) "OS=hi3535" > config.mk

DEBUG:
	@$(ECHO) "BVDEBUG=yes" >> config.mk


